/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * File glob specifying which files to include.
 */
export type Path = string;

export interface Schema {
  /**
   * The url of Tolgee API.
   */
  apiUrl?: string;
  /**
   * Tolgee API Key. Can be a Project API Key or a Personal Access Token.
   */
  apiKey?: string;
  /**
   * Project ID. Only required when using a Personal Access Token.
   */
  projectId?: number | string;
  /**
   * A path to a custom extractor to use instead of the default one.
   */
  extractor?: string;
  /**
   * File glob patterns to your source code, used for keys extraction.
   */
  patterns?: string[];
  /**
   * Format for push and pull operations.
   */
  format?:
    | "JSON"
    | "JSON_TOLGEE"
    | "XLIFF"
    | "PO"
    | "APPLE_STRINGS_STRINGSDICT"
    | "APPLE_XLIFF"
    | "ANDROID_XML"
    | "FLUTTER_ARB"
    | "PROPERTIES"
    | "YAML_RUBY"
    | "YAML";
  push?: {
    /**
     * File glob specifying which files to include.
     */
    path?: string;
    records?: Record[];
    [k: string]: unknown;
  };
  pull?: {
    /**
     * File
     */
    path?: string;
    /**
     * List of languages to pull. Leave unspecified to export them all.
     */
    languages?: string[];
    /**
     * List of translation states to include. Defaults all except untranslated.
     */
    states?: ("UNTRANSLATED" | "TRANSLATED" | "REVIEWED")[];
    /**
     * List of namespaces to pull. Defaults to all namespaces.
     */
    namespaces?: string[];
    [k: string]: unknown;
  };
  /**
   * Structure delimiter to use. By default, Tolgee interprets `.` as a nested structure. You can change the delimiter, or disable structure formatting by not specifying any value to the option.
   */
  delimiter?: string | null;
  [k: string]: unknown;
}
export interface Record {
  path?: Path;
  language?: string;
  namespace?: string;
  [k: string]: unknown;
}
