/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  /**
   * The url of Tolgee API.
   */
  apiUrl?: string;
  /**
   * Tolgee API Key. Can be a Project API Key or a Personal Access Token.
   */
  apiKey?: string;
  /**
   * Project ID. Only required when using a Personal Access Token.
   */
  projectId?: number | string;
  /**
   * A path to a custom extractor to use instead of the default one.
   */
  extractor?: string;
  /**
   * File glob patterns to include
   */
  patterns?: string[];
  /**
   * Path to folder with localization files for push/pull commands.
   */
  path?: string;
  /**
   * Format of the exported files.
   */
  format?: string;
  /**
   * List of languages to pull. Leave unspecified to export them all.
   */
  languages?: string[];
  /**
   * List of translation states to include. Defaults all except untranslated.
   */
  states?: ("UNTRANSLATED" | "TRANSLATED" | "REVIEWED")[];
  /**
   * Structure delimiter to use. By default, Tolgee interprets `.` as a nested structure. You can change the delimiter, or disable structure formatting by not specifying any value to the option.
   */
  delimiter?: string | null;
  /**
   * List of namespaces to pull. Defaults to all namespaces.
   */
  namespaces?: string[];
  [k: string]: unknown;
}
